### PR TITLE
add an erb template for the te-agent.cfg file

### PR DESCRIPTION
**Pull request by drenalin23**
# Description 
This PR has cookstyle fixes everywhere.  Adds an erb template for the te-agent.cfg file and an attribute (currently defaults to false) for using the template instead of the shell script to generate the config file on first run.

# Why
In our environment the shell script never finishes on first run and we can't finish the first chef run on provision cleanly.  It is preferable to write out the config file from an erb template.

### CODE REVIEW

**Comment by pcabido** [comment]
@drenalin23 After reviewing this, I actually think this should be the default behavior and the shell script should be removed.
There was an old config, `bind-addr` that we used to rely on. It has since been deprecated and removed. Most of that shell script's logic was to find the main interface and use it. 
That also renders the `interface` and `ip_version` useless. They can be removed.

The code looks good to me, I've tested it and it works as expected. The question I have for you is, given you made these changes, do you want to go a step forward and remove the script and make the config the default mode or do you prefer that I merge now and have the team take care of that change?

**Comment by drenalin23** [comment]
I'll submit an update.  Sounds like a good plan.

**Comment by drenalin23** [comment]
If this looks good we can merge and then submit a PR to cut a 0.3.0 release.
Have you considered submitting this to supermarket.chef.io?

**Comment by pcabido** [comment]
@drenalin23 thanks for the work on this.

We have never discussed adding it to supermarket.chef.io, I will look into that. Thanks for the tip.

**Pull request merged**
